package:
  name: wqio
  version: "0.6.1"

source:
  git_url: https://github.com/Geosyntec/wqio.git
  git_tag: v0.6.1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - scipy
    - matplotlib
    - statsmodels
    - seaborn
    - mpl-probscale

  run:
    - python
    - setuptools
    - pandas
    - seaborn
    - statsmodels
    - xlrd
    - six
    - mpl-probscale

test:
  imports:
    - wqio
    - wqio.utils

about:
  home: https://github.com/International-BMP-Database/wqio.git
  license:  BSD License
  summary: 'Basic water quality inflow/outflow analysis tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
