package:
  name: wqio
  version: 0.7.3

source:
  path: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  script: python -m pip install . --no-deps --no-build-isolation -vv
  number: 12

requirements:
  host:
    - python >=3.12
    - pip
    - uv-build >=0.12,<0.13

  run:
    - python >=3.12
    - numpy
    - scipy
    - pandas <3
    - matplotlib
    - seaborn
    - statsmodels
    - mpl-probscale

test:
  requires:
    - pytest
    - pytest-mpl
    - ipython

  imports:
    - wqio
    - wqio.utils

  commands:
    - python -c "import sys, wqio; sys.exit(wqio.test())"

about:
  home: https://github.com/International-BMP-Database/wqio.git
  license:  BSD License
  summary: 'Basic water quality inflow/outflow analysis tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
