package:
  name: wqio
  version: 0.6.1

source:
  path: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  script: python setup.py install
  number: 12

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - scipy
    - matplotlib
    - statsmodels
    - seaborn
    - mpl-probscale

  run:
    - python
    - setuptools
    - pandas
    - seaborn
    - statsmodels
    - xlrd
    - six
    - mpl-probscale

test:
  requires:
    - pytest
    - pytest-mpl
    - ipython

  imports:
    - wqio
    - wqio.utils

  commands:
    - python -c "import sys, wqio; sys.exit(wqio.test())"

about:
  home: https://github.com/International-BMP-Database/wqio.git
  license:  BSD License
  summary: 'Basic water quality inflow/outflow analysis tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
