name: Run coverage via codecov
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Code Coverage
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set up Python 3.13
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.13"
    - name: Generate coverage report
      run: |
        uv sync --locked
        uv run coverage run --source wqio check_wqio.py --doctest-modules --cov --cov-report=xml
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}
